# Home Work 01 
1. Numpy 
1. Pytorch (tensor (basic operations))

# DEADLINE

### IS-142 - 08.10.24 
### IS-141 - 15.10.24

## BLOKE №1 (numpy) 

1. Импортировать NumPy под именем np

In [2]:
import numpy as np


2. Создать вектор (одномерный массив) размера 20, заполненный нулями

In [8]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

3. Создать вектор размера 20, заполненный числом 1.75

In [11]:
np.full((20),1.75)

array([1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75,
       1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75])

4. Создать вектор со значениями от 4 до 31

In [14]:
np.arange(4, 32, 1)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

5. Развернуть вектор (первый становится последним)

In [20]:
np.arange(4, 32)[::-1]


array([31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4])

6. Создать матрицу (двумерный массив) 3x3 со значениями от 1 до 9

In [29]:
np.reshape(np.arange(1, 10, 1), (3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7. Создать 3x3 единичную матрицу

In [24]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Создать 4x4 пустую матрицу

In [21]:
np.empty((4,4))

array([[4.64757490e-310, 0.00000000e+000, 2.41907520e-312,
        2.14321575e-312],
       [2.46151512e-312, 2.31297541e-312, 2.35541533e-312,
        2.05833592e-312],
       [2.22809558e-312, 2.56761491e-312, 2.48273508e-312,
        2.05833592e-312],
       [2.05833592e-312, 2.29175545e-312, 2.07955588e-312,
        2.14321575e-312]])

9. Создать единичную матрицу 4x4 со сдвигом на единицу вниз относительно главной диагонали

In [22]:
np.eye(4, 4, -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

10. Создать тензор 3x3x3 со случайными значениями

In [6]:
np.random.random((3,3,3))

array([[[0.75534793, 0.15335813, 0.28507211],
        [0.3879728 , 0.04967174, 0.48135059],
        [0.88835176, 0.57260965, 0.95054442]],

       [[0.93853984, 0.22326793, 0.8066197 ],
        [0.15835389, 0.62360505, 0.13690071],
        [0.84727965, 0.65096701, 0.92716504]],

       [[0.85818459, 0.54090467, 0.35776641],
        [0.82679617, 0.21992577, 0.22749261],
        [0.35499066, 0.88219396, 0.22763054]]])

11. Создать массив 5x5 со случайными значениями, найти минимум и максимум

In [15]:
A = np.random.random((5,5))
print(A)
print(np.min(A))
print(np.max(A))

[[0.95866217 0.04127306 0.52551354 0.19029604 0.38143896]
 [0.3156127  0.32628287 0.49137314 0.90242954 0.14001233]
 [0.02297377 0.4736566  0.2686871  0.25053715 0.33967162]
 [0.13980184 0.9167942  0.31971408 0.12809243 0.00856989]
 [0.14424537 0.19812705 0.97786699 0.48963594 0.09936301]]
0.008569890390194734
0.9778669933612524


12. Создать случайный вектор размера 50 и найти среднее значение всех элементов

In [26]:
A = np.random.random((50))
print(A)
print(np.mean(A))

[0.06969806 0.21153508 0.94896193 0.55329153 0.41912463 0.76935315
 0.37392603 0.70751351 0.34627842 0.70954469 0.62889113 0.28524264
 0.05147067 0.68845397 0.40970442 0.29056331 0.53303589 0.95912108
 0.20061425 0.23001779 0.2241019  0.774664   0.19393308 0.51413088
 0.82908745 0.00874303 0.94814345 0.25290196 0.78277683 0.2374742
 0.59719476 0.69589974 0.60284508 0.51672195 0.40290105 0.59621769
 0.90853322 0.92418719 0.64623259 0.04230427 0.38253963 0.61086739
 0.14783054 0.05757043 0.53444227 0.25487623 0.10279028 0.28883667
 0.21197534 0.82198224]
0.46998094995943623


13. Создать матрицу с 0 внутри, и 1 на границах

In [65]:
matrix = np.ones((5, 5), dtype = int)  
matrix[1:-1, 1:-1] = 0 
print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


14. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [18]:
arr = np.array([1, 2, 3 ,4 ])
np.diag(arr, -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

15. Перемножить матрицы 5x3 и 3x2

In [20]:
mat = np.random.random((5,3))
mat1 = np.random.random((3, 2))
print(mat)
print(mat1)
print(np.dot(mat, mat1))

[[0.2025699  0.40101816 0.43190236]
 [0.09283438 0.20510704 0.74084578]
 [0.55514777 0.83811448 0.69282076]
 [0.82336822 0.06815567 0.85487562]
 [0.77324279 0.54155709 0.31271388]]
[[0.83166831 0.67209544]
 [0.84660332 0.33082354]
 [0.82743187 0.09564907]]
[[0.86534406 0.31012361]
 [0.86385112 0.201109  ]
 [1.74451129 0.71664794]
 [1.44982141 0.65769758]
 [1.36031499 0.72876358]]


16. Создать вектор состоящий из 15 элементов, поменять знак у элементов, значения которых между 6 и 12 

In [33]:
vec = np.arange(15)
vec = np.where((vec > 6) & (vec < 12), -vec, vec)
print(vec)

[  0   1   2   3   4   5   6  -7  -8  -9 -10 -11  12  13  14]


17. Создать 2 матрицы A(3x3) и B(3x3), получить матрицу С путем поэлеметного умножения.

In [ ]:
A = np.arange(9).reshape(3,3)
B = np.arange(10, 19).reshape(3,3)
C = A * B
print(C)

[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]


18. Найти максимальные и минимальные значения матрицы С по строкам и столбцам

In [42]:
A = np.arange(9).reshape(3,3)
B = np.arange(10, 19).reshape(3,3)
C = A * B
C[2][1] = 150
print(C)
print(np.max(C, axis = 0)) # столбец
print(np.max(C, axis = 1)) # строка
print(np.min(C, axis = 0)) # столбец
print(np.min(C, axis = 1)) # строка

[[  0  11  24]
 [ 39  56  75]
 [ 96 150 144]]
[ 96 150 144]
[ 24  75 150]
[ 0 11 24]
[ 0 39 96]


19. Создать вектор со значениями от 0 до 1 c 10 наблюдениями

In [38]:
np.random.random(10)


array([0.67028477, 0.65466747, 0.3074418 , 0.37490163, 0.39819331,
       0.80912462, 0.69717832, 0.20711713, 0.80882421, 0.99369785])

20. Отсортировать вектор

In [23]:
vec = np.arange(15, 0, -1)
print(vec)
print(np.sort(vec))

[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


21. Проверить, одинаковы ли 2 numpy массива

In [35]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
print(np.array_equal(a, b))

True


22. Сделать массив неизменяемым

In [66]:
arr = np.array([1, 2, 3])
arr.flags.writeable = False 
arr[0] = 3

ValueError: assignment destination is read-only

23. Создать случайный вектор из 20 элементов, найти квантиль от 10% и от 80%

In [44]:
vec = np.arange(20)
print(np.quantile(vec, 0.1))
print(np.quantile(vec, 0.8))

1.9000000000000001
15.200000000000001


24. Создать массив любой размерности состоящий из int и string

In [54]:
np.array([1, 2,  "str"],dtype = object)


array([1, 2, 'str'], dtype=object)

25. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [ ]:
print(np.finfo(np.float64).min) 
print(np.iinfo(np.int64).min)
## меняем ,узнаем остальные.


-1.7976931348623157e+308
-9223372036854775808


26. Преобразовать массив из float в int

In [58]:
vec = np.array([1.2, 3.5])
print(vec.dtype)
vec = vec.astype(np.int64)
print(vec.dtype)
print(vec)

float64
int64
[1 3]


27. Отнять среднее из каждой строки в матрице

In [48]:
mat = np.arange(25).reshape(5,5)
print(mat)
mat = mat - np.average(mat)
print(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[-12. -11. -10.  -9.  -8.]
 [ -7.  -6.  -5.  -4.  -3.]
 [ -2.  -1.   0.   1.   2.]
 [  3.   4.   5.   6.   7.]
 [  8.   9.  10.  11.  12.]]


28. 

Дана данные из файла.

1,2,3,4,5

6,,,7,8

,,9,10,11

Необходимо прочитать его


In [ ]:
import numpy as np
import io

# Исходная строка
str_data = "1,2,3,4,5\n6,,,7,8\n,,9,10,11"

data = np.genfromtxt(io.StringIO(str_data), delimiter=",", dtype=float)

print(data)


[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


29. Посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [46]:
vec = np.arange(1,10000)
vec = np.power(vec,2)
print(np.sum(vec))

333283335000


## BLOKE №2 (tensors) 

1. Импортируйте pytorch

In [4]:
import torch


2. Создать вектор состящий из 10 элементов

In [3]:
torch.empty(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Создать тензор из python list

In [27]:
torch.tensor([1, 2, 3, 4, 5])

tensor([1, 2, 3, 4, 5])

4. Создать тензор из np.array

In [10]:
torch.tensor(np.array([1, 2, 3, 4, 5]))

tensor([1, 2, 3, 4, 5])

5. Создать тензор с нормальным распределением

In [8]:
torch.randn(3,3)


tensor([[-1.3165,  0.0921,  0.4379],
        [-1.0987,  1.3901,  0.7556],
        [ 0.5183, -0.9251,  0.7718]])

6. Создать тензор размером 3х3х3

In [7]:
torch.randn(3,3,3)

tensor([[[ 0.4712,  1.0092, -0.3479],
         [-0.5240,  0.0773,  1.8535],
         [ 0.0400, -0.0450, -0.2111]],

        [[ 0.2977,  0.1869, -0.0382],
         [-0.3762, -1.4439, -0.5544],
         [-0.1260, -0.3439, -0.5278]],

        [[ 1.7295, -0.9962,  2.9198],
         [ 0.0628,  1.0352,  1.1672],
         [-0.0356,  0.9669,  0.0057]]])

7. Создать единичную матрицу размером 4х5

In [9]:
torch.eye(4,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

8. Создать вектор размера 25, заполнить элементами со значением pi

In [15]:
torch.full([25], np.pi)

tensor([3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
        3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
        3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416])

9. Умножить матрицу размера 9, заполненная от 0 до 8, поэлементно на любое число

In [20]:
A = torch.tensor(np.arange(9).reshape(3,3))
A = torch.multiply(A,3)
print(A)


tensor([[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]])


10. Создать произвольный тензор с типом данных int8

In [22]:
torch.tensor([1,2, 3, 4], dtype = torch.int8)

tensor([1, 2, 3, 4], dtype=torch.int8)

11. Изменить тип данных из пункта 10 на int64

In [24]:
torch.tensor([1,2, 3, 4], dtype = torch.int64)

tensor([1, 2, 3, 4])

12. Создать случайный тензор размера 4x5 и найти среднее по 2му столбцу.

In [9]:
A = torch.arange(9).reshape(3,3)
print(A)
torch.mean(A.float(),dim = 0)[1]

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor(4.)

13. Создать пустой тензор произвольных размеров

In [25]:
torch.empty(32)

tensor([-1.5933e+01,  4.5873e-41, -1.5933e+01,  4.5873e-41,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         7.7052e+31,  7.2148e+22,  1.5766e-19,  1.0256e-08,  1.0255e-08,
         3.0270e+12,  1.0839e-08,  1.0549e-08,  1.7090e-04,  1.2963e+16,
         2.1707e-18,  7.0952e+22,  1.7748e+28,  1.8176e+31,  7.2708e+31,
         5.0778e+31,  3.2608e-12,  1.7728e+28,  7.0367e+22,  2.1715e-18,
         1.3435e-05,  3.3857e-06])

14. Скалярно умножить 2 вектора

In [38]:
A = torch.randn(3)
B = torch.randn(3)
C = torch.dot(A,B)
print(C)

tensor(-0.2890)


15. Умножить матрицу на вектор

In [47]:
A = torch.arange(1,10).reshape(3,3)
B = torch.tensor([1,2,3])
C = torch.matmul(A,B)
print(C)
print(A)

tensor([14, 32, 50])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


16. Перемножить 2D матрицы 

In [48]:
A = torch.arange(1,10).reshape(3,3)
B = torch.arange(10, 19).reshape(3,3)
C = torch.matmul(A, B)
print(C)
print(A)
print(B)

tensor([[ 84,  90,  96],
        [201, 216, 231],
        [318, 342, 366]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])


17. Перемножить 3D тензоры

In [52]:
A = torch.arange(27).reshape(3,3,3)
B = torch.arange(27).reshape(3,3,3)
C = torch.matmul(A, B)
print(C)


tensor([[[  15,   18,   21],
         [  42,   54,   66],
         [  69,   90,  111]],

        [[ 366,  396,  426],
         [ 474,  513,  552],
         [ 582,  630,  678]],

        [[1203, 1260, 1317],
         [1392, 1458, 1524],
         [1581, 1656, 1731]]])


18. Создать вектор с нормальным распределением и вывести элементы больше 0.5

In [35]:
A = torch.randn(10)
A[A > 0.5]

tensor([1.5970, 1.0969, 0.8087])

19. Создать матрицу 3х3 заполненную единицами и заменить 1й столбец на 4

In [18]:
A = torch.ones(3,3)
A[: , 0] = 4
print(A)

tensor([[4., 1., 1.],
        [4., 1., 1.],
        [4., 1., 1.]])


20. Создать матрицу и вывести сумму по каждой строке

In [14]:
A = torch.ones(3,3)
torch.sum(A)
torch.sum(A)
torch.sum(A)

tensor(9.)

20. Создать матрицу и вывести среднее по каждому столбцу

In [23]:
A = torch.arange(9).reshape(3,3)
print(A)
print(torch.mean(A.float(),dim = 0))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([3., 4., 5.])


21. Создать 2 вектора и сконкатенировать по 1 оси

In [24]:
A = torch.arange(4)
B = torch.arange(4)
torch.concat([A,B])

tensor([0, 1, 2, 3, 0, 1, 2, 3])

22. Перемножим две большие единичные матрицы. 
Сначал на центральном процессоре, затем попробуйте на GPU

In [ ]:
import time

size = 5000 


A = torch.ones(size, size, dtype=torch.float32)
B = torch.ones(size, size, dtype=torch.float32)


start = time.time()
C_cpu = torch.matmul(A, B)
end = time.time()
print(f"Время умножения на CPU: {end - start:.4f} сек")


device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Используем устройство: {device}")

A_gpu = A.to(device)
B_gpu = B.to(device)

start = time.time()
C_gpu = torch.matmul(A_gpu, B_gpu) 
torch.cuda.synchronize() 
end = time.time()
print(f"Время умножения на GPU: {end - start:.4f} сек")


Время умножения на CPU: 0.5562 сек
Используем устройство: cuda
Время умножения на GPU: 0.1069 сек
